[astronaut-sddm-theme]
src.git = "https://github.com/Keyitdev/sddm-astronaut-theme"
fetch.github = "Keyitdev/sddm-astronaut-theme"

[coc-tailwindcss3]
src.git = "https://github.com/yaegassy/coc-tailwindcss3"
fetch.github = "yaegassy/coc-tailwindcss3"

[copilot-vim]
src.git = "https://github.com/github/copilot.vim"
fetch.github = "github/copilot.vim"

[fleet]
src.git = "https://github.com/dimensionhq/fleet"
fetch.github = "dimensionhq/fleet"
cargo_locks = [ "Cargo.lock" ]

[nvim-cokeline]
src.git = "https://github.com/noib3/nvim-cokeline"
fetch.github = "noib3/nvim-cokeline"

[zscroll]
src.git = "https://github.com/noctuid/zscroll"
fetch.github = "noctuid/zscroll"
